language: node_js
node_js:
  - "0.10"
branches:
  only:
  - test01
install:
  - npm install phantomjs -g
  - npm install -g mocha-phantomjs
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
before_script:
  - phantomjs --version
  - mocha-phantomjs --version
  - chmod 0777 ./node_modules/.bin/mocha
  - gulp &
  - sleep 5 # give gulp background task some time to execute.
script:
  - make test