version: '3'
services:
  web:
    image: docker-node-express-mongoapp
    #build: ./web-site
    command: node app.js
    ports:
      - "8000:8000"
    volumes:
      #- ./web-site:/usr/src/app
      - /volumes/Matrix/learning/NodeJS/SDM_INFS809:/usr/src/appg08 
      #- /usr/src/app/node_modules
      - /Users/phucpebble/mongo-data:/data/db
    #depends_on:
      #- "mongo"
     # - phucpebble/aut-group08
  mongo:
    #image: "mongo"
    image: "newnodejs"
    ports:
      - "27017:27017"
 # adminmongo:
    #image: "mrhenry/surveydb"

 #  ports:
   #   - "1234:1234"